### PR TITLE
Fix local development with Pub/Sub emulator

### LINKED ISSUE #41: Cloud events incorrectly unmarshalled: first argument is undefined, 2nd argument differs from production
When Pubsub notifications are sent to a locally hosted cloud event function, the first argument is undefined. It should contain the event information. The 2nd argument though present, does not match production signature; rather than containing metadata about the notification, it contains the entire event object, which should be the contents of argument 1 instead.

## My dummy cloud events function:

```js
exports.helloEvents = (data, context) => {
  console.log(data);
  console.log(context);
};
```

Pub/sub notification being sent:

```js
{
  "subscription": "projects/myproj/subscriptions/mysub",
  "message": {
    "data": "...my base 64 encoded data...",
    "messageId": "1",
    "attributes": {}
  }
}
```

## helloEvents log in production:
Argument 1, data, is:

```js
{  
   "subscription":"projects/myproj/subscriptions/mysub",
   "message":{  
      "data":"...my base 64 encoded data...",
      "messageId":"1",
      "attributes":{}
   }
}
```

Argument 2, context, is:
```js
{  
   "eventId":"12032d95-089a-4663-9be5-8aafd9d4c623",
   "resource":{  
      "service":"pubsub.googleapis.com",
      "name":"projects/myproj/topics/mytopic"
   },
   "eventType":"google.pubsub.topic.publish",
   "timestamp":"2019-06-16T18:39:44.809Z"
}
```

## On local, the results I get is very different.

- Argument 1: undefined
- Argument 2: 
```js
{  
   "subscription":"projects/myproj/subscriptions/mysub",
   "message":{  
      "data":"...my base 64 encoded data...",
      "messageId":"1",
      "attributes":{}
   }
}
```

### LINKED ISSUE #96: Event parsing doesn't match Cloud Functions in background mode
Hey there!

Related to #41 and #85, I ran into a lot of confusion trying to sort out what the format should be for the request body to a local [background function](https://cloud.google.com/functions/docs/writing/background).

In production a background function has the following for the first parameter:

```
{ @type: 'type.googleapis.com/google.pubsub.v1.PubsubMessage',
  attributes: null,
  data:  '<base64 data>' }
```

and the following for the "context" parameter:

```
{ eventId: '749799261766789',
  timestamp: '2019-09-17T19:56:09.018Z',
  eventType: 'providers/cloud.pubsub/eventTypes/topic.publish',
  resource: '<pubsub topic>' }
```

The [current docs](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/de6ef3874ae703084d5b7566ecde743a8f80bd36/docs/events.md) for using the functions framework for events suggests `curl`ing data in a format that results in the parameters not matching the above - the first parameter becomes:

```
{ message:
   { attributes: {},
     data: '<base64 data>',
     messageId: '136969346945' },
  subscription: 'projects/myproject/subscriptions/mysubscription' }
```

And the "context" parameter:

```
{ type: 'true',
  specversion: 'true',
  source: 'true',
  id: 'true' }
```

Digging into the source code, https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/de6ef3874ae703084d5b7566ecde743a8f80bd36/src/invoker.ts#L431-L447 seems to expect the body (for "legacy events") to look something like:

```
{ data:
  { data: '<base64 data>`,
    attributes: null,
    @type: 'type.googleapis.com/google.pubsub.v1.PubsubMessage' },
  eventId: 749799261766789 }
```

(Further evidence this is expected is in this [WIP branch](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1255/files#diff-a5c7e60c1ae9d8d39557244c08a97e48R47) for NodeJS samples.)

Using the above POST body seems to result in function parameters that most closely match production, and although it doesn't match [the POST body for push messages](https://cloud.google.com/pubsub/docs/push#receiving_push_messages) I'm assuming that's what users should send if they want their function to act closest to what they will see when they deploy to Cloud Functions.

Is this correct?

### PR DESCRIPTION
**Pull request by matthewrobertson**
Currently, deploying a function with `--trigger-topic` creates a Pub/Sub subscription that delivers events to an internal endpoint that marshals request payloads before forwarding them to a user's function. Unfortunately, this breaks local development with the Pub/Sub emulator as the Functions Frameworks are dependent on this request marshalling logic. 

In order to better support local development and testing with the Pub/Sub emulator, this commit introduces the event marshalling logic to the Functions Framework via express middleware that is enable when the `PUBSUB_EMULATOR_HOST` is set.

fixes #41, fixes #96

### CODE REVIEW

File: test/middleware.ts [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+        },
+        context: {
+            eventId: '1', 
+            eventType: 'google.pubsub.topic.publish', 
+            resource: {
+               name: 'projects/FOO/topics/BAR_TOPIC', 
+               service: 'pubsub.googleapis.com', 
+               type: 'type.googleapis.com/google.pubsub.v1.PubsubMessage'
+            },
+            timestamp: new Date().toISOString(),
```
Comment (matthewrobertson) [inline test/middleware.ts:61]: This will cause flaky tests. We need to add a dependency to freeze the clock in unit tests.

File: src/server.ts [hunk 2]
```diff
@@ -97,6 +98,13 @@ export function getServer(
   // http://expressjs.com/en/advanced/best-practice-security.html#at-a-minimum-disable-x-powered-by-header
   app.disable('x-powered-by');
 
+  // If a Pub/Sub subscription is configured to invoke a user's function directly, the request body
+  // needs to be marshalled into the structure that wrapEventFunction expects. This unblocks local
+  // development with the Pub/Sub emulator
+  if (functionSignatureType === SignatureType.EVENT) {
```
Comment (grant) [inline src/server.ts:104]: Don't we need to add `PUBSUB_EMULATOR_HOST` check somewhere?

File: src/middleware.ts [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+interface RawPubSubBody {
+  subscription: string;
+  message: {
+    data: string;
+    messageId: string;
+    attributes: {[key: string]: string};
+  };
+}
+
+interface PubSubEventBody {
```
Comment (grant) [inline src/middleware.ts:30]: - Can we put interfaces in `src/functions.ts` with our other interfaces?
- Can we partially re-use / extend an existing interface?

File: src/middleware.ts [hunk 4]
```diff
@@ -0,0 +1,131 @@
...
+// See the License for the specific language governing permissions and
+// limitations under the License.
+import {Request, Response, NextFunction} from 'express';
+
+const PUBSUB_EVENT_TYPE = 'google.pubsub.topic.publish';
+const PUBSUB_MESSAGE_TYPE =
+  'type.googleapis.com/google.pubsub.v1.PubsubMessage';
+const PUBSUB_SERVICE = 'pubsub.googleapis.com';
+
+interface RawPubSubBody {
```
Comment (grant) [inline src/middleware.ts:21]: nit: Can you add a comment for every interface?

File: src/middleware.ts [hunk 5]
```diff
@@ -0,0 +1,131 @@
+// Copyright 2019 Google LLC
```
Comment (grant) [inline src/middleware.ts:1]: nit: Can we be a bit more specific with this file? I'd recommend `middlewarePubSub.ts`, `middlewareHelper.ts`, or something similar. We define middleware elsewhere in the repo and may have unrelated to Pub/Sub middleware in the future.

File: src/middleware.ts [hunk 6]
```diff
@@ -0,0 +1,131 @@
...
+  );
+};
+
+/**
+ * Extract the Pub/Sub topic name from the HTTP request path.
+ * @param path the URL path of the http request
+ * @returns the Pub/Sub topic name if the path matches the expected format,
+ * null otherwise
+ */
+const extractTopic = (path: string): string | null => {
```
Comment (grant) [inline src/middleware.ts:77]: nit: rename to `extractPubSubTopic`

File: src/middleware.ts [hunk 7]
```diff
@@ -0,0 +1,131 @@
...
+interface MarshalledPubSubRequest extends Request {
+  body: PubSubEventBody;
+}
+
+/**
+ * Type predicate that checks if a given Request is a RawPubSubRequest
+ * @param request a Request object to typecheck
+ * @returns true if this Request is a RawPubSubRequest
+ */
+const isRawPubSubRequest = (request: Request): request is RawPubSubRequest => {
```
Comment (grant) [inline src/middleware.ts:61]: I'd imagine the return type to be `boolean`.

File: src/middleware.ts [hunk 8]
```diff
@@ -0,0 +1,131 @@
...
+  };
+}
+
+interface RawPubSubRequest extends Request {
+  body: RawPubSubBody;
+}
+
+interface MarshalledPubSubRequest extends Request {
+  body: PubSubEventBody;
+}
```
Comment (grant) [inline src/middleware.ts:54]: Can we comment as to what these interfaces do / mean?

File: src/middleware.ts [hunk 9]
```diff
@@ -0,0 +1,131 @@
...
+};
+
+/**
+ * Marshal the body of an HTTP request from a Pub/Sub subscription
+ * @param req an unmarshalled http request from a Pub/Sub push subscription
+ * @returns the marshalled request body expected by wrapEventFunction
+ */
+const marshalPubSubRequestBody = (req: RawPubSubRequest): PubSubEventBody => ({
+  context: {
+    eventId: req.body.message.messageId,
```
Comment (grant) [inline src/middleware.ts:97]: Do we want to a more null safe access?

`req?.body?.message?.messageId`

We might get a bad body.

File: src/middleware.ts [hunk 10]
```diff
@@ -0,0 +1,131 @@
...
+ * @param res express response object
+ * @param next function used to pass control to the next middle middleware function in the stack
+ */
+export const legacyPubSubEventMiddleware = (
+  req: Request,
+  res: Response,
+  next: NextFunction
+) => {
+  if (isRawPubSubRequest(req)) {
+    ((req as unknown) as MarshalledPubSubRequest).body = marshalPubSubRequestBody(
```
Comment (grant) [inline src/middleware.ts:126]: Can we add a comment to explain the type casting?

**Review by grant — CHANGES_REQUESTED** [review]
Thanks!

Do you mind adding a little more detailed description in the PR for how you tested this locally?

For example, I don't see the use of `PUBSUB_EMULATOR_HOST` in the PR here. Some light instructions for how a user can test this manually would help. Even better would be to update [the docs we have on this content](https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/docs/events.md) with the new setup.

File: src/middleware.ts (hunk 9 above)
Comment (matthewrobertson) [reply src/middleware.ts:97]: The Typechecker is protecting against this. The type predicate `isRawPubSubRequest` validates that all these fields are not undefined and that information is carried through the type system.

File: src/middleware.ts (hunk 10 above)
Comment (matthewrobertson) [reply src/middleware.ts:126]: Maybe this isn't the most clear way to write this. I will update it.

File: src/server.ts (hunk 2 above)
Comment (matthewrobertson) [reply src/server.ts:104]: You are right, my original idea was that this would check `process.env['PUBSUB_EMULATOR_HOST'] != null` here, but I wanted to put this up as an idea after thinking about @di's comments offline. Here we just treat this as any event conversion, where we detect the payload structure does not match the requested signature type and marshal it. This removes friction from the dev workflow: it just works out of the box without additional setup. It also improves portability of event functions (I can point my Pub/Sub push subscription at a function running in on any server with this change). The cost is some risk that we marshal an even that we aren't supposed to, but I think the benefits outweigh the risk as the current behaviour is clearly broken.

What do you think?

File: src/middleware.ts (hunk 5 above)
Comment (matthewrobertson) [reply src/middleware.ts:1]: I can update this. My thinking was eventually when we have more middleware, we would create `middleware/index.ts` and then imports for this module would stay the same...

File: src/middleware.ts (hunk 3 above)
Comment (matthewrobertson) [reply src/middleware.ts:30]: One bit I am confused about, this interface is a private implementation detail of the logic in this module. My understanding is the stuff in `functions.ts` is that it is public for clients of the framework.

File: src/pubsub_middleware.ts [hunk 11]
```diff
@@ -0,0 +1,144 @@
...
+  return null;
+};
+
+/**
+ * Marshal the body of an HTTP request from a Pub/Sub subscription
+ * @param body an unmarshalled http request body from a Pub/Sub push subscription
+ * @param path the HTTP request path
+ * @returns the marshalled request body expected by wrapEventFunction
+ */
+const marshalPubSubRequestBody = (body: RawPubSubBody, path: string) => ({
```
Comment (grant) [inline src/pubsub_middleware.ts:109]: Do you mind annotating the return type for this function?

```ts
(body: RawPubSubBody, path: string): ??? => ({
```

File: test/pubsub_middleware.ts [hunk 12]
```diff
@@ -0,0 +1,102 @@
...
+  message: {
+    data: 'eyJmb28iOiJiYXIifQ==',
+    messageId: '1',
+    attributes: {
+      test: '123'
+    }
+  }
+};
+
+const marshalledPubSubBody = (topic: string | null) => ({
```
Comment (grant) [inline test/pubsub_middleware.ts:31]: nit: Would be nice to have return type.

File: src/server.ts (hunk 2 above)
Comment (di) [reply src/server.ts:104]: (This makes sense to me!)

Comment (grant) [reply src/server.ts:104]: Hmm.

Isn't the supervisor modifying GCF payloads such that GCF Pub/Sub prod works fine but FF Pub/Sub local doesn't? As long as we're sure that this version of the FF will work with prod, I suppose we're fine.

Perhaps `isRawPubSubRequestBody` evals to false in GCF.

File: src/middleware.ts (hunk 3 above)
Comment (grant) [reply src/middleware.ts]: For interfaces that developers will use to re-create HTTP POST request event payloads, they should be exported in the `functions.ts`. Otherwise, if private – no user will ever import it – then okay to keep private.

Public interfaces are kept in that file and exposed as stated here: https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/package.json#L10

File: src/server.ts (hunk 2 above)
Comment (matthewrobertson) [reply src/server.ts:104]: > Perhaps `isRawPubSubRequestBody` evals to false in GCF.

Yes exactly, if the supervisor has already marshalled the payload, the request body will be different, and this middleware will be a no-op.

File: src/middleware.ts (hunk 3 above)
Comment (matthewrobertson) [reply src/middleware.ts]: OK I think it makes sense to keep this one private then.
